# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [2]:
import numpy as n

#### Q2 : Afficher la version de numpy et la configuration 

In [3]:
n.show_config()
n.__version__

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


'1.19.2'

#### Q3 : Créer un vecteur nul de taille 10

In [4]:
n.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [5]:
v=n.zeros(10)
v[3]=1
print (v)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [6]:
Z=n.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [7]:
n.flip(Z)


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [8]:
n.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [9]:
n.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [10]:
n.arange(0, 27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [11]:
n.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [12]:
a=n.random.rand(5)
print(a)
a.sum()

[0.39456914 0.36886819 0.33134143 0.31036847 0.53755526]


1.9427024962984296

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [13]:
n.random.rand(5).mean()

0.41276177809751946

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [14]:
l = [x for x in range(11)]
n.size(l)

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [15]:
a=n.random.rand(10)
print(a)

[0.02557423 0.78541475 0.71652333 0.85764172 0.72693187 0.8950777
 0.26547186 0.22784664 0.68177143 0.42566345]


#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [40]:
A = n.random.rand(5)
#=[1,1,1,1,1]
#B =[1,1,1,1,1]
B = n.random.rand(5)
g=A==B
if(g.any()!=True):
    print (False)
else : print(True)


False


#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [43]:
A=n.random.rand(10)
A.astype(n.float32)
print(A)
A.astype(n.int32)

[0.96575095 0.18377695 0.72668385 0.90467873 0.98224463 0.75252513
 0.56556919 0.34143463 0.98746558 0.08200376]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [45]:
A = n.random.rand(5)*10
print(A)
norm=n.linalg.norm(A)
print(norm)
AN=A/norm
print(AN)

[2.83901184 6.00492707 2.4376541  2.9337342  8.02264496]
11.091930546440192
[0.2559529  0.54137799 0.21976824 0.26449266 0.72328662]


#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [49]:
M=n.mat(n.random.rand(2)*10,n.random.rand(2)*10)
print(M)
n.transpose(M)

TypeError: Cannot construct a dtype from an array

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)